#!/bin/bash -l

##########################################################
#
#       MALT ANALYSIS (v0.1.2)
#
#       Luis Arriola
#       Last Update: 18th May 2016
#
##########################################################
#
#
###  Requires:
#		- MALT v0.1.2
#       - modules:
#               -Java
#               
#       - index (generated with malt-build)
#		- Folder with fastq/fastq.gz files to be analized
#
###

if [ $# == 0 ]; then
	echo    "	Usage: malt_multi_0_1_2.sh <INPUT_DATA_DIR/FILE> <MALT_INDEX_DIR>
		INPUT_DATA_DIR: Directory with the input data files or FILE in FASTQ or FASTQ.GZ format
		MALT_INDEX_DIR: Directory with the INDEX generated by malt-build"
else
	# Loading Modules, and defining Index and License locations
	module load /opt/shared/system/Modules/modulefiles/java/java-1.7.09
	module list

	INDEX=$2
	LICENSE="/data/acad/Luis_DC_backup/MALT/00_License/MEGAN5-academic-license.txt"
	export PATH=/home/users/larriola/software/malt:$PATH

	# MALT
	echo -e "Starting Analysis...\n";date
	# Input File or directory
	if [[ -d $1 ]]; then
		SEQS=`ls -dm $1/* | tr "," " "| tr "\\n" " "`
		OUT_SEQS=`echo $(ls -m $1| tr "," " "| tr "\\n" " "| sed 's/\.\w*\.*\w*/_MALT\.sam/g')`
	else
		SEQS=$1
		OUT_SEQS=$(basename "$SEQS" | cut -d. -f1)_MALT.sam
	fi

	echo "malt-run -t 16 -i $SEQS -a $OUT_SEQS -d $INDEX -m BlastX -L $LICENSE -v"
	malt-run -t 16 -i $SEQS -a $OUT_SEQS -d $INDEX -m BlastX -L $LICENSE -v

	# SAM2RMA
	mkdir SAM_"$1"
	mv *.sam.gz SAM_"$1"
	unpigz SAM_"$1"/*
	echo "running SAM2RMA"
	~/Scripts/run_SAM2RMA.sh SAM_"$1"

	echo "END"; date
fi
